pipeline {
	agent {
		label 'master'
		}
	stages {
		stage("Create docker image") {
			steps ('Build') {
				echo "========= start building image ========="
				app = docker.build("./docker/toolbox")
				dir ('docker/toolbox') {
					sh 'docker build . '
				}
			}
		}
		stage('Test image') {
			steps {
				junit '**/build/test-report/*.xml'		 
				app.inside {
					sh 'echo "Tests passed"'
				}
			
			}
		}	
		stage('Push image') {
			steps{ 
				script{	
					docker.withRegistry('https://ec2-34-218-253-89.us-west-2.compute.amazonaws.com', 'DockerHost') {
					app.push("${env.BUILD_NUMBER}")
					app.push("latest")
					}
				}
			}
		}
	}
}
