pipeline {
	agent {
		label 'master'
		}
	stages {
		stage("Create docker image") {
			steps {
				echo "========= start building image ========="
				dir ('docker/toolbox') {
					sh 'docker build . '
					}
				}
			}
		stage('Test image') {
			 sh '''
			 if ! docker inspect docker-image &> /dev/null; then
				 echo 'docker-image does not exist!'
				 exit 1
			 fi
			 '''
		}	
		stage('Push image') {
			docker.withRegistry('https://ec2-34-218-253-89.us-west-2.compute.amazonaws.com', 'DockerHost') {
				app.push("${env.BUILD_NUMBER}")
				app.push("latest")
			} 
		}
	}
}
