// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
	agent {
		label 'master'
		}
	options {
		buildDiscarder(logRotator(numToKeepStr" '10', artifactNumToKeepStr: '10'))
		timestamps()
		}
	stages {
		stage("Create docker image") {
			steps {
				echo "========= start building image ========="
				dir ('docker/toolbox') {
					sh 'docker build . '
					}
				}
			}
		stage('Test image') {
			 sh '''
			 if ! docker inspect docker-image &> /dev/null; then
				 echo 'docker-image does not exist!'
				 exit 1
			 fi
			 '''
		}	
		stage('Push image') {
			docker.withRegistry('https://.com') {
				app.push("${env.BUILD_NUMBER}")
				app.push("latest")
			} 
		}
	}
}
